#!/Users/mahlstrom/workspace/awsssh/venv/bin/python
import sys
from src.awsssh import awsssh


def print_help():
    print("Here is some help")


if __name__ == "__main__":
    if len(sys.argv) <= 1 or sys.argv[1] == '--help':
        print_help()
        exit()

    server_name=sys.argv[1]
    awsssh(server_name)
